# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_res', '0002_auto_20170421_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='reservations',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
