# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_res', '0004_auto_20170421_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
