# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_res', '0005_auto_20170421_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
